services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:- root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:- root}
      POSTGRES_DB: ${POSTGRES_DB:- root}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
